# Generated by Django 5.2.4 on 2025-07-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Список мастеров'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Список услуг'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_approved', 'Не подтверждён'), ('approved', 'Подтвержден'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменён')], default='not_approved', max_length=50, verbose_name='Статус'),
        ),
    ]
