# Generated by Django 5.2.4 on 2025-07-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
