# Generated by Django 5.2.4 on 2025-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_date_created_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='address',
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price'], name='core_servic_price_72c8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_popular'], name='core_servic_is_popu_7bf01a_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price', 'duration'], name='core_servic_price_dac576_idx'),
        ),
    ]
